### ISSUE TITLE
Question about text length

### ISSUE THREAD

**Issue by mariembenslama** [Holmeyoung/crnn_pytorch#1]
Can it be trained on any text length?

**Comment by Holmeyoung** [comment]
> Can it be trained on any text length?

@mariembenslama Hi, it's length should be smaller than 26.

**Comment by mariembenslama** [comment]
Ok, Thanks 😄

**Comment by mariembenslama** [comment]
Also it makes sense, the image name = random_word and the name can't be a text 😁

**Comment by Holmeyoung** [comment]
@mariembenslama Hi, if your train sample is big enough, you can make the image name = 'aaa', 'bbb', 'aab'. And because some symbol can't appear in image path(name) like` \ / * ?`, so you can use `file mode` to make train data. My English is not so good, i don't know if i answer your question :eyes:.

**Comment by mariembenslama** [comment]
It's alright :) :D 
It's the same thing with file mode you will name the image with / and , ....etc.
So even that method it won't work 😁 I tried it.
The best thing is just to remove the / and [ etc.

Thanks for the answer :D

**Comment by Holmeyoung** [comment]
@mariembenslama Hi, you can change the image name but leave the label. For example
`train.txt`
```
/root/data/1.jpg
/*aaa
/root/data/2.jpg
[bbb
.
.
.
```
Have you tried this way?

**Comment by mariembenslama** [comment]
Yes!! It works well! Thanks 🎉🎉😄😄😄😄

**Comment by mariembenslama** [comment]
There's one question that I couldn't find the answer: why do we change it to the lmdb format? Why is it necessary?

Sorry for asking a lot 😥

**Comment by mariembenslama** [comment]
There's one question that I couldn't find the answer: why do we change it to the lmdb format? Why is it necessary?

Sorry for asking a lot 😥

**Comment by Holmeyoung** [comment]
@mariembenslama Hi, it doesn't matter. In fact i don't konw why. But it's not necessary and you and load data while training. I guess the reason is: through lmdb, we only need to make data once. In general, we need to retrain to fine tune the params and see the performance.  So if we load data from disk and convert the image to tensor everytime training the model, it will slow down the training process a lot.

**Comment by mariembenslama** [comment]
I understand :D Thanks for the answer, also yes, we must retrain the model 2 times to fine tune the params.

Thank you very much again 😊🎶

**Comment by aaobscure** [comment]
@mariembenslama 

Hi,

I have a question,

I want to train on my dataset ( Farsi Language ), I cannot understand what the shape of the dataset should be?

In my problem, all of my images in the dataset have 5 sentences ( 3 numbers, 2 names), can you tell me how to prepare for training?

I have to crop all of them, or I can train them in one image ( I mean all the 5 sentences in one image).

For example :
Sentence 1 : niddal
Sentece 2: 10/2/10
Sentence 3: Imam
.....

Best,
